---- REQUERIMIENTO FUNCIONAL RF2 - REGISTRO DE EMPLEADOS Y CLIENTES
--- Sentencias SQL para el registro de empleados y clientes

-- USO
-- Copie el contenido deseado de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña utilizada

--GERENTE
INSERT INTO EMPLEADOS(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_ROL, NOMBRE, CORREO_ELECTRONICO, SALARIO) VALUES(1053868600, 1, 1, 4, 'Rafael Nunez', 'ohgloriainmarcesible@ohjubiloinmortal.com', 8000000);

--ADMINISTRADOR DE DATOS
INSERT INTO EMPLEADOS(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_ROL, NOMBRE, CORREO_ELECTRONICO, SALARIO) VALUES(1053868601, 1, 1, 3, 'Belisario Betancur', 'devuelvanamihijo@milmillones.com', 5000000);

--RECEPCIONISTAS
INSERT INTO EMPLEADOS(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_ROL, NOMBRE, CORREO_ELECTRONICO, SALARIO) VALUES(1053868603, 1, 1, 1, 'Ivan Duque', 'economianaranja@trescerditos.com', 2000000);
INSERT INTO EMPLEADOS(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_ROL, NOMBRE, CORREO_ELECTRONICO, SALARIO) VALUES(1053868604, 1, 1, 1, 'Ivan Marquez', 'welcometothejungle@jubiladosfarc.com', 2000000);

--EMPLEADOS
INSERT INTO EMPLEADOS(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_ROL, NOMBRE, CORREO_ELECTRONICO, SALARIO) VALUES(1053868605, 1, 1, 2, 'Ivanka Trump', 'botox@quierobotox.com', 200000);
INSERT INTO EMPLEADOS(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_ROL, NOMBRE, CORREO_ELECTRONICO, SALARIO) VALUES(1053868606, 1, 1, 2, 'Melania Trump', 'masbotox@quierobotox.com', 200000);
INSERT INTO EMPLEADOS(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_ROL, NOMBRE, CORREO_ELECTRONICO, SALARIO) VALUES(1053868607, 1, 1, 2, 'Donald Trump', 'botoxhastalamuerte@quierobotox.com', 200000);
INSERT INTO EMPLEADOS(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_ROL, NOMBRE, CORREO_ELECTRONICO, SALARIO) VALUES(1053868608, 1, 1, 2, 'George Bush', '911@autoatentado.com', 200000);

--CLIENTES
INSERT INTO CLIENTES(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_RESERVA_HABITACION, ID_RESERVA_SERVICIO, NOMBRE, CORREO_ELECTRONICO) VALUES (1053868609, 1,1,1,1,'Luis Miguel Gomez Londono','lm.gomezl@uniandes.edu.co');
INSERT INTO CLIENTES(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_RESERVA_HABITACION, ID_RESERVA_SERVICIO, NOMBRE, CORREO_ELECTRONICO) VALUES (1053868610, 1,1,2,2,'Cesar Neyit Galindo Forero','lm.plinpinl@uniandes.edu.co');
INSERT INTO CLIENTES(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_RESERVA_HABITACION, ID_RESERVA_SERVICIO, NOMBRE, CORREO_ELECTRONICO) VALUES (1053868611, 1,1,3,3,'Miguel Andres Londono Carrascal','lm.goez@uniandes.edu.co');
INSERT INTO CLIENTES(ID, TIPO_IDENTIFICACION, ID_HOTEL, ID_RESERVA_HABITACION, ID_RESERVA_SERVICIO, NOMBRE, CORREO_ELECTRONICO) VALUES (1053868612, 1,1,4,4,'Luis Carlos Goez Londono','lm.pop@uniandes.edu.co');


