---- REQUERIMIENTO FUNCIONAL RF5 - REGISTRO DE SERVICIOS
--- Sentencias SQL para el registro de servicios

-- USO
-- Copie el contenido deseado de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña utilizada
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(1, 1, 'Piscina', '8', '21', 'Entretenimiento', 'Piscina con agua');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(2, 1, 'Gimnasio', '5', '21', 'Deportes', 'Pesas y mas');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(3, 1, 'Internet', '00', '23', 'Entretenimiento', '4G');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(4, 1, 'Bar', '11', '23', 'Entretenimiento', 'Mucho trago eaa');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(5, 1, 'Restaurante', '8', '21', 'Alimentacion', 'Italianissimo, VellaVita');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(6, 1, 'Supermercado', '8', '20', 'Alimentacion', 'JumboRullaXito');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(7, 1, 'Tienda', '8', '20', 'Ocio', 'Louis Gualtron');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(8, 1, 'Spa', '8', '20', 'Relajacion', 'da');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(9, 1, 'Lavanderia', '8', '18', 'Necesidad', 'Huele a chucha');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(10, 1, 'Prestamo', '8', '18', 'Bienestar', 'Amarrado');
INSERT INTO SERVICIOS(ID, ID_HOTEL, NOMBRE, HORA_APERTURA, HORA_CIERRE, TIPO, DESCRIPCION) VALUES(11, 1, 'Salon', '8', '21', 'Ejecutivos', 'de clase');

---Productos/Menu
--Bar
INSERT INTO PRODUCTOS(ID, ID_SERVICIO, NOMBRE, VALOR) VALUES (1, 4, 'Jack Daniels', 150000);
INSERT INTO PRODUCTOS(ID, ID_SERVICIO, NOMBRE, VALOR) VALUES (2, 4, 'Aguardiente Cristal', 70000);
INSERT INTO PRODUCTOS(ID, ID_SERVICIO, NOMBRE, VALOR) VALUES (3, 4, 'Cerveza Andina', 2000);
--Restaurante
INSERT INTO PRODUCTOS(ID, ID_SERVICIO, NOMBRE, VALOR) VALUES (4, 5, 'BMT', 13000);
INSERT INTO PRODUCTOS(ID, ID_SERVICIO, NOMBRE, VALOR) VALUES (5, 5, 'Ciabatta', 15000);
INSERT INTO PRODUCTOS(ID, ID_SERVICIO, NOMBRE, VALOR) VALUES (6, 5, 'Spaghetti Bolognesa', 19000);