---- REQUERIMIENTO FUNCIONAL RF6 - REGISTRO DE PLANES DE CONSUMO
--- Sentencias SQL para el registro de planes de consumo

-- USO
-- Copie el contenido deseado de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña utilizada
INSERT INTO PLANES_DE_CONSUMO(ID, ID_HOTEL, TIPO_PLAN_DE_CONSUMO, MINIMO_DE_NOCHES, DESCUENTO, COSTO_FIJO) VALUES(1, 1, 1, 8, 5, 1600000);
INSERT INTO PLANES_DE_CONSUMO(ID, ID_HOTEL, TIPO_PLAN_DE_CONSUMO, MINIMO_DE_NOCHES, DESCUENTO, COSTO_FIJO) VALUES(2, 1, 2, 7, 10, 1800000);
INSERT INTO PLANES_DE_CONSUMO(ID, ID_HOTEL, TIPO_PLAN_DE_CONSUMO, MINIMO_DE_NOCHES, DESCUENTO, COSTO_FIJO) VALUES(3, 1, 3, 1, 15, 2000000);
INSERT INTO PLANES_DE_CONSUMO(ID, ID_HOTEL, TIPO_PLAN_DE_CONSUMO, MINIMO_DE_NOCHES, DESCUENTO, COSTO_FIJO) VALUES(4, 1, 4, 3, 8, 700000);