SELECT g.ID_HABITACION, SUM(p.VALOR)
FROM ((RESERVAS_HABITACIONES r INNER JOIN HABITACIONES h ON r.ID=h.ID AND r.FECHA_INICIO<='18/03/2019' AND r.FECHA_FIN>='19/03/2019') INNER JOIN GASTOS g on g.ID_HABITACION=h.ID) INNER JOIN PRODUCTOS p ON g.ID_PRODUCTO=p.ID
GROUP BY g.ID_HABITACION;