SELECT ID
FROM CLIENTES 
WHERE ID NOT IN 
(SELECT C.ID FROM CLIENTES C INNER JOIN RESERVAS_SERVICIOS R ON C.ID = R.ID_CLIENTE 
	WHERE R.ID_SERVICIO =7 AND R.HORA_APERTURA >= '25/05/2018' AND R.HORA_CIERRE <= '28/05/2019') 
AND ROWNUM<126 
GROUP BY ID