SELECT C.NOMBRE,C.ID, COUNT(R.ID) AS SERVICIOS_CONSUMIDOS 
FROM CLIENTES C, RESERVAS_HABITACIONES R, GASTOS G, PRODUCTOS P 
WHERE C.ID=R.ID_CLIENTE 
AND G.ID_RESERVA_HABITACION=R.ID 
AND G.ID_PRODUCTO=P.ID 
AND ((R.CHECKED_IN=1 AND R.CHECKED_OUT=1) OR (P.VALOR>300000) OR  (P.ID_SERVICIO=8 OR P.ID_SERVICIO=11)) 
AND ROWNUM<126 
GROUP BY C.NOMBRE,C.ID 
ORDER BY COUNT(R.ID) DESC;