SELECT COUNT(ROUND(FECHA_DE_GASTO, 'DDD')) CONSUMIDO_X_VECES, ROUND(FECHA_DE_GASTO, 'DDD') GASTO_GENERADO_EL
FROM GASTOS g INNER JOIN HABITACIONES h ON h.ID = g.ID_HABITACION
WHERE g.FECHA_DE_GASTO < SYSTIMESTAMP
AND g.FECHA_DE_GASTO > add_months(SYSTIMESTAMP, -1)
AND TIPO_HABITACION = 3
GROUP BY ROUND(FECHA_DE_GASTO, 'DDD')
ORDER BY 
COUNT(ROUND(FECHA_DE_GASTO, 'DDD')) DESC, ROUND(FECHA_DE_GASTO, 'DDD');