SELECT *
FROM (SELECT c.ID as CEDULA, SUM(p.Valor) as TOTAL_CONSUMIDO
FROM ((CLIENTES c INNER JOIN RESERVAS_HABITACIONES rH ON c.ID_RESERVA_HABITACION = rH.ID)
INNER JOIN GASTOS g ON g.ID_HABITACION = rH.ID_HABITACION)
INNER JOIN PRODUCTOS p ON p.ID = g.ID_PRODUCTO
GROUP BY c.ID
ORDER BY TOTAL_CONSUMIDO DESC)
WHERE TOTAL_CONSUMIDO >= 15000000;

