/*
EL WHERE DE ESTE ARCHIVO ES PARA DEMOSTRAR LOS DATOS, EN EL PROGRAMA SON VARIABLES.
*/
SELECT c.ID AS CEDULA, COUNT(r.ID) as NUM_RESERVAS
FROM CLIENTES c INNER JOIN RESERVAS_SERVICIOS r ON c.ID = r.ID_CLIENTE
WHERE r.ID_SERVICIO = 10
AND r.HORA_APERTURA >= '23/05/2019'
AND r.HORA_CIERRE <= '28/05/2019'
GROUP BY c.ID
ORDER BY NUM_RESERVAS DESC;