--- Sentencias SQL para la creación del esquema de el hotel andes

-- USO
-- Copie el contenido deseado de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña utilizada
    
--eliminar los datos de la BD
DELETE FROM EMPLEADOS;
DELETE FROM GASTOS;
DELETE FROM HABITACIONES;
DELETE FROM RESERVAS;
DELETE FROM CLIENTES;
DELETE FROM PLANES_DE_CONSUMO;
DELETE FROM SERVICIOS_HOTELES;
DELETE FROM HOTELES;
DELETE FROM RESERVAS_MANTENIMIENTOS;
DELETE FROM RESERVAS_CONVENCIONES;
DELETE FROM TIPOS_RESERVA_HABITACION;
DELETE FROM TIPOS_IDENTIFICACION;
DELETE FROM TIPOS_PLAN_DE_CONSUMOS;
DELETE FROM TIPOS_ROL;
DELETE FROM TIPOS_MANTENIMIENTOS;
DELETE FROM PRODUCTOS;
DELETE FROM RESERVAS_HABITACIONES;
DELETE FROM RESERVAS_SERVICIOS;
DELETE FROM SERVICIOS;
DELETE FROM CONVENCIONES;


-- Eliminar todas las tablas de la base de datos
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE GASTOS CASCADE CONSTRAINTS;
DROP TABLE HABITACIONES CASCADE CONSTRAINTS;
DROP TABLE RESERVAS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE PLANES_DE_CONSUMO CASCADE CONSTRAINTS;
DROP TABLE SERVICIOS_HOTELES CASCADE CONSTRAINTS;
DROP TABLE HOTELES CASCADE CONSTRAINTS;
DROP TABLE RESERVAS_MANTENIMIENTOS CASCADE CONSTRAINTS;
DROP TABLE RESERVAS_CONVENCIONES CASCADE CONSTRAINTS;
DROP TABLE TIPOS_RESERVA_HABITACION CASCADE CONSTRAINTS;
DROP TABLE TIPOS_IDENTIFICACION CASCADE CONSTRAINTS;
DROP TABLE TIPOS_PLAN_DE_CONSUMOS CASCADE CONSTRAINTS;
DROP TABLE TIPOS_ROL CASCADE CONSTRAINTS;
DROP TABLE TIPOS_MANTENIMIENTOS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE RESERVAS_HABITACIONES CASCADE CONSTRAINTS;
DROP TABLE RESERVAS_SERVICIOS CASCADE CONSTRAINTS;
DROP TABLE SERVICIOS CASCADE CONSTRAINTS;
DROP TABLE CONVENCIONES CASCADE CONSTRAINTS;
COMMIT;

