SELECT h.ID FROM HABITACIONES h LEFT JOIN RESERVAS_HABITACIONES hr ON hr.ID=h.ID
WHERE hr.ID IS NULL AND h.TIPO_HABITACION=2;

SELECT c.FECHA_FIN 
FROM CONVENCIONES c 
INNER JOIN RESERVAS_CONVENCIONES rc 
ON c.ID=rc.ID_CONVENCION AND rc.ID_HABITACION=9;

SELECT c.FECHA_FIN 
FROM CONVENCIONES c
WHERE c.ID=74;

SELECT c.FECHA_INICIO FROM CONVENCIONES c WHERE c.ID=74;

SELECT c.FECHA_FIN FROM CONVENCIONES c INNER JOIN RESERVAS_CONVENCIONES rc ON c.ID=rc.ID_CONVENCION AND rc.ID_HABITACION=11;

SELECT h.ID
FROM ((HABITACIONES h LEFT JOIN RESERVAS_HABITACIONES hr ON hr.ID=h.ID) LEFT JOIN (RESERVAS_CONVENCIONES rc INNER JOIN CONVENCIONES c ON rc.ID_CONVENCION = c.ID) ON rc.ID_HABITACION = h.ID)
WHERE (hr.ID IS NULL OR hr.FECHA_FIN < '13/05/2019') AND (rc.ID IS NULL OR c.FECHA_INICIO < '13/05/2019') AND h.TIPO_HABITACION=2;

ALTER TABLE RESERVAS_HABITACIONES
  ADD PAZ_Y_SALVO NUMBER(1) NOT NULL;
  
SELECT *
FROM (
((RESERVAS_CONVENCIONES rc INNER JOIN CONVENCIONES c ON rc.ID_CONVENCION = c.ID) 
LEFT JOIN RESERVAS_HABITACIONES rh ON rh.ID_HABITACION = rc.ID_HABITACION)
)
WHERE rc.ID_SERVICIO !=;